---
#
# Ansible managed
#
repository:
  description: Install and configure haproxy on your system.
  homepage: https://robertdebock.nl/
  topics: cloud, haproxy, networking, ansible, molecule, tox, playbook
