---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-haproxy
      haproxy_frontends:
        - name: http
          address: "*"
          port: 80
          default_backend: backend
        - name: https
          address: "*"
          port: 443
          default_backend: backend
          ssl: yes
          crts:
            - /tmp/haproxy.keycrt
        - name: smtp
          address: "*"
          port: 25
          default_backend: smtp
          mode: tcp
      haproxy_backend_default_balance: roundrobin
      haproxy_backends:
        - name: backend
          httpcheck: yes
          balance: roundrobin
          servers: "{{ groups['all'] }}"
          port: 8080
          options:
            - check
        - name: smtp
          httpcheck: yes
          balance: roundrobin
          servers: "{{ groups['all'] }}"
          port: 25
          options:
            - check
