---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install testing requirements
      ansible.builtin.package:
        name: socat
        state: present
      notify:
        - Uninstall testing requirements

    - name: Check if port responds
      ansible.builtin.wait_for:
        port: "{{ item }}"
      loop:
        - 80
        - 443

    - name: Check of content can be retrieved
      ansible.builtin.uri:
        url: "{{ item }}"
        validate_certs: no
        status_code:
          - 200
      loop:
        - "http://localhost/"
        - "https://localhost/"

    - name: Check if stats are available
      ansible.builtin.shell:
        cmd: "echo 'show stat' | socat unix-connect:/var/lib/haproxy/stats stdio"
      changed_when: no

  handlers:
    - name: Uninstall testing requirements
      ansible.builtin.package:
        name: socat
        state: absent
